### PR TITLE
Spark 2.4 support

### PR DESCRIPTION
**Pull request by shimamoto**
ref #23

### CODE REVIEW

**Comment by shimamoto** [comment]
[SPARK-25047](https://issues.apache.org/jira/browse/SPARK-25047)

**Comment by shimamoto** [comment]
@takezoe Can you take a look?

**Comment by takezoe** [comment]
LGTM! I didn't know this Scala 2.12 issue...

**Comment by shimamoto** [comment]
Yeah, same here. It looks like this is affected by circular references in Java object graph when objects use a serialization proxy like LambdaMetaFactory. 😕  Thanks for review! @takezoe

**Pull request merged**
