### PR TITLE
Updating the build with a new Spark version.

### PR DESCRIPTION
**Pull request by ChetanBhasin**
This creates a new version of the library with the latest release of Spark as mentioned in https://github.com/bizreach/aws-kinesis-scala/issues/6

### CODE REVIEW

**Comment by ChetanBhasin** [comment]
Fixes: https://github.com/bizreach/aws-kinesis-scala/issues/6

**Comment by shimamoto** [comment]
@ChetanBhasin Thank you for this PR! We have not released version 0.0.4 yet, which supports Scala 2.12. At first, we are going to release version 0.0.4. Soon afterward, we will merge this and release version 0.0.5. Please give us a few days.

**Comment by ChetanBhasin** [comment]
@shimamoto Sure! Thanks for the update.

**Comment by ChetanBhasin** [comment]
@shimamoto Hi! Has this been pushed to maven central?

**Comment by shimamoto** [comment]
@ChetanBhasin I've been working on it. Just a second please. Probably I will push version 0.0.5 to maven central this evening :)

**Comment by ChetanBhasin** [comment]
Sure! Thanks :)

**Pull request merged**
